[package]
name = "temp_tray-rs"
version = "0.1.0"
authors = ["Werner1201 <werner.romling@unigranrio.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
imageproc = "0.21"
rusttype = "0.9"
systray = "0.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1.0"