name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  OPENWEATHER_API_KEY: "1ed014973f3aff63e2ec5bbb95751ef4"

jobs:
  build:

   runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
    - name: Build
      run: cargo build --verbose
    - uses: actions/checkout@master  
    - name: Run tests
      run: cargo test --verbose
    
    

    
